<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10</LangVersion>
    <GameDir>$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim</GameDir>
    <Managed>$(GameDir)/Valheim.app/Contents/Resources/Data/Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx" HintPath="$(GameDir)/BepInEx/core/BepInEx.dll" Private="false" />
    <Reference Include="assembly_valheim" HintPath="$(Managed)/publicized_assemblies/assembly_valheim_publicized.dll" Private="false" />
    <Reference Include="assembly_utils" HintPath="$(Managed)/publicized_assemblies/assembly_utils_publicized.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(Managed)/UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(Managed)/UnityEngine.CoreModule.dll" Private="false" />
  </ItemGroup>
</Project>
