namespace More_World_Locations_AIO;

public class AssetPaths
{
    public static string[] assetPathsInBundleFull = new[]
    {
        // Meadows Pack 1
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins2.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins3.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins6.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins7.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_Ruins8.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_RuinsArena1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_RuinsArena3.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_RuinsChurch1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_RuinsWell1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MaypoleHut1.prefab",
        
        // Black Forest Pack 1
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsArena2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsCastle1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsCastle3.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsTower3.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsTower6.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinsTower8.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_Tavern1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_WoodTower1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_WoodTower2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_WoodTower3.prefab",
        
        // Meadows Pack 2
        "Assets/WarpProjects/More World Locations/Meadows/MWL_DeerShrine1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_DeerShrine2.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsBarn1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsHouse2.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsRuin1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsTomb4.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsTower1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_OakHut1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_SmallHouse1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsFarm1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsLighthouse1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsSawmill1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsWall1.prefab",
        "Assets/WarpProjects/More World Locations/Meadows/MWL_MeadowsTavern1.prefab",

        // Black Forest Pack 2
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestForge1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestForge2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestGreatHouse2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestHouse2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestRuin1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestTower2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestTower3.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_MassGrave1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_StoneFormation1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_GuardTower1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RootRuins1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RootsTower1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RootsTower2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestRuin2.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestRuin3.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestSkull1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestTower4.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestTower5.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestPillar1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_CoastTower1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestCamp1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RuinedTower1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_ForestGrove1.prefab",
        "Assets/WarpProjects/More World Locations/Blackforest/MWL_RockShrine1.prefab",

        // Swamp Pack 1
        "Assets/WarpProjects/More World Locations/Swamp/MWL_GuckPit1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampAltar1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampAltar2.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampAltar3.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampAltar4.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampCastle2.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampGrave1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampHouse1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampRuin1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampTower1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampTower2.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampTower3.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampWell1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_AbandonedHouse1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_Treehouse1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_Shipyard1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_FortBakkarhalt1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_Belmont1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampCourtyard1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampBrokenTower1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampBrokenTower3.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_TreeTowers1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_CastleCorner1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_StoneCircle1.prefab",
        "Assets/WarpProjects/More World Locations/Swamp/MWL_SwampTemple1.prefab",
        
        // Mountains Pack 1
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneCastle1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneFort1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneHall1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneTavern1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneTower1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneTower2.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_WoodBarn1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_WoodFarm1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_WoodHouse1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_TempleShrine1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_StoneAltar1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_MountainDvergrShrine1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_MountainDvergrShrine2.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_MountainOverlook1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_MountainCultShrine1.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_RuinsChurch2.prefab",
        "Assets/WarpProjects/More World Locations/Mountain/MWL_MountainShrine1.prefab",

        // Plains Pack 1
        "Assets/WarpProjects/More World Locations/Plains/MWL_GoblinFort1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingRock1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingVillage1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingVillage2.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_PlainsPillar1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTemple1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTemple2.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTemple3.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTempleBroken1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTemple4.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingWall1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_FulingTower1.prefab",
        "Assets/WarpProjects/More World Locations/Plains/MWL_RockGarden1.prefab",

        // Mistlands Pack 1
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistFort2.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_SecretRoom1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistWorkshop1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistTower1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistWall1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistTower2.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistHut1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistHut2.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_DvergrEitrSingularity1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_DvergrHouse1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_DvergrHouseWood1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_DvergrHouseWood2.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MarbleJail1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MarbleHome1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MarbleCliffAltar1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistPond1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MarbleCage1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_DvergrKnowledgeExtractor1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_AncientShrine1.prefab",
        "Assets/WarpProjects/More World Locations/Mistlands/MWL_MistShrine1.prefab",
        
        // Ashlands Pack 1
        "Assets/WarpProjects/More World Locations/Ashlands/MWL_AshlandsFort1.prefab",
        "Assets/WarpProjects/More World Locations/Ashlands/MWL_AshlandsFort2.prefab",
        "Assets/WarpProjects/More World Locations/Ashlands/MWL_AshlandsFort3.prefab",
        
        // Ports
        "Assets/WarpProjects/More World Locations/Ports/MWL_Port1.prefab",
        "Assets/WarpProjects/More World Locations/Ports/MWL_Port2.prefab",
        "Assets/WarpProjects/More World Locations/Ports/MWL_Port3.prefab",
        "Assets/WarpProjects/More World Locations/Ports/MWL_Port4.prefab",
    };
    
    public static string[] assetPathsInBundle4 = new[]
    {
        // Ashlands Pack 1
        "Assets/WarpProjects/LocationTesting/Location1.prefab",
    };
}